# Generated by Django 5.0.1 on 2024-01-24 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial'),
    ]

    operations = [
    ]
